/*
 * Copyright 2024-2025 Amazon.com, Inc. or its affiliates.
 */

import { RemovalPolicy } from "aws-cdk-lib";
import {
  BlockPublicAccess,
  Bucket,
  BucketAccessControl,
  BucketEncryption,
  ObjectOwnership
} from "aws-cdk-lib/aws-s3";
import { NagSuppressions } from "cdk-nag";
import { Construct } from "constructs";

import { OSMLAccount } from "../types";
import { DataplaneConfig } from "./dataplane";

/**
 * Properties for creating metadata storage resources.
 */
export interface MetadataStorageProps {
  /** The OSML account configuration. */
  readonly account: OSMLAccount;
  /** The dataplane configuration. */
  readonly config: DataplaneConfig;
  /** The removal policy for resources. */
  readonly removalPolicy: RemovalPolicy;
}

/**
 * Construct that manages the S3 bucket for storing processed image metadata.
 *
 * This construct encapsulates the creation and configuration of the S3
 * bucket used to store processed image metadata files (AUX, GDAL INFO, OVR)
 * generated by the Data Intake Lambda function.
 */
export class MetadataStorage extends Construct {
  /** The S3 bucket for storing processed image metadata. */
  public readonly outputBucket: Bucket;

  /**
   * Creates a new MetadataStorage construct.
   *
   * @param scope - The scope/stack in which to define this construct
   * @param id - The id of this construct within the current scope
   * @param props - The properties for configuring this construct
   */
  constructor(scope: Construct, id: string, props: MetadataStorageProps) {
    super(scope, id);

    const bucketName = `${props.config.S3_OUTPUT_BUCKET_NAME}-${props.account.id}`;
    const prodLike = props.account.prodLike || false;

    // Create S3 bucket for output data with OSML-compatible settings
    this.outputBucket = new Bucket(this, "DIOutputBucket", {
      bucketName: bucketName,
      autoDeleteObjects: !prodLike,
      enforceSSL: true,
      encryption: BucketEncryption.KMS_MANAGED,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      removalPolicy: props.removalPolicy,
      objectOwnership: ObjectOwnership.OBJECT_WRITER,
      versioned: prodLike,
      accessControl: BucketAccessControl.BUCKET_OWNER_FULL_CONTROL
    });

    // Add cdk-nag suppressions
    NagSuppressions.addResourceSuppressions(
      this.outputBucket,
      [
        {
          id: "AwsSolutions-S1",
          reason:
            "Server access logging is not required for the metadata storage bucket. The bucket is used for internal data processing and access is controlled via IAM policies. CloudTrail provides audit logging for S3 API calls."
        },
        {
          id: "AwsSolutions-S2",
          reason:
            "Versioning is enabled for production-like accounts. For non-production accounts, versioning is disabled to reduce storage costs. The bucket uses lifecycle policies and removal policies appropriate for the environment."
        }
      ],
      true
    );
  }
}
