# Copyright 2024-2025 Amazon.com, Inc. or its affiliates.

FROM public.ecr.aws/lambda/python:3.13 AS integration-test

RUN dnf -y upgrade && \
    dnf -y install gcc ca-certificates && \
    dnf clean all && \
    rm -rf /var/cache/dnf

COPY docker/requirements-ingest.txt ./requirements.txt
RUN pip3 install --no-cache-dir --root-user-action=ignore -r requirements.txt

# Copy the function code to the LAMBDA_TASK_ROOT directory
ADD . ${LAMBDA_TASK_ROOT}

# Install the package
RUN pip3 install --no-cache-dir --root-user-action=ignore .

# Copy test data to the container
RUN mkdir -p /opt/test/data
COPY test/data/small.tif /opt/test/data/small.tif

# Set entry point
CMD ["test.integ.handler.handler"]
