# Copyright 2024-2025 Amazon.com, Inc. or its affiliates.

FROM public.ecr.aws/lambda/python:3.13 AS stac

RUN dnf -y upgrade && \
    dnf -y install gcc ca-certificates && \
    dnf clean all && \
    rm -rf /var/cache/dnf

COPY docker/requirements-stac.txt ./requirements.txt
RUN pip3 install --no-cache-dir --root-user-action=ignore -r requirements.txt

EXPOSE 8080

CMD ["stac_fastapi.opensearch.app.handler"]
